# Generated by Django 5.2.6 on 2025-10-16 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No-show"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "MED_APPOINTMENT",
                "ordering": ["-date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Schedule",
                "verbose_name_plural": "Doctor Schedules",
                "db_table": "MED_DOCTOR_SCHEDULE",
                "ordering": ["doctor", "day_of_week"],
            },
        ),
        migrations.CreateModel(
            name="DoctorTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name": "Doctor Turn",
                "verbose_name_plural": "Doctor Turns",
                "db_table": "MED_DOCTOR_TURN",
                "ordering": ["doctor_schedule", "start_time"],
            },
        ),
    ]
