# Allow local connections
local   all             all                                     trust

# Allow replication connections from any Docker network address using password
host    replication     all     0.0.0.0/0     md5
host    all             all     0.0.0.0/0     md5