# Generated by Django 5.2.6 on 2025-10-16 17:08

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "status",
                    models.IntegerField(choices=[(0, "Inactive"), (1, "Active")], default=1, verbose_name="status"),
                ),
                (
                    "activate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for an immediate activation", null=True),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for indefinite activation", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                ("website_url", models.URLField(blank=True, null=True)),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("address", models.CharField(max_length=255, verbose_name="Street Address")),
                (
                    "city",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities_light.city"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities_light.country"
                    ),
                ),
                (
                    "enterprise_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_medical_specialities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities_light.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
                "db_table": "MED_CLINIC",
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "status",
                    models.IntegerField(choices=[(0, "Inactive"), (1, "Active")], default=1, verbose_name="status"),
                ),
                (
                    "activate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for an immediate activation", null=True),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for indefinite activation", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "enterprise_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="disease", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "db_table": "MED_DISEASE",
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "status",
                    models.IntegerField(choices=[(0, "Inactive"), (1, "Active")], default=1, verbose_name="status"),
                ),
                (
                    "activate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for an immediate activation", null=True),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for indefinite activation", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "enterprise_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speciality",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Speciality",
                "verbose_name_plural": "Specialities",
                "db_table": "MED_SPECIALITY",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "status",
                    models.IntegerField(choices=[(0, "Inactive"), (1, "Active")], default=1, verbose_name="status"),
                ),
                (
                    "activate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for an immediate activation", null=True),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for indefinite activation", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "enterprise_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="test", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
                "db_table": "MED_TEST",
            },
        ),
        migrations.CreateModel(
            name="ClinicDoctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_doctor",
                        to="medicalApp.clinic",
                    ),
                ),
                (
                    "doctor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Doctor",
                "verbose_name_plural": "Clinics Doctors",
                "db_table": "MED_CLINIC_DOCTOR",
                "unique_together": {("doctor_user", "clinic")},
            },
        ),
        migrations.CreateModel(
            name="ClinicSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="medicalApp.clinic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Schedule",
                "verbose_name_plural": "Clinic Schedules",
                "db_table": "MED_CLINIC_SCHEDULE",
                "ordering": ["clinic", "day_of_week"],
                "unique_together": {("clinic", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="DoctorSpeciality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                (
                    "doctor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_speciality",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_speciality",
                        to="medicalApp.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Speciality",
                "verbose_name_plural": "Doctors Specialities",
                "db_table": "MED_DOCTOR_SPECIALITY",
                "unique_together": {("doctor_user", "speciality")},
            },
        ),
        migrations.CreateModel(
            name="ClinicSpeciality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_speciality",
                        to="medicalApp.clinic",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_speciality",
                        to="medicalApp.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Speciality",
                "verbose_name_plural": "Clinic Specialities",
                "db_table": "MED_CLINIC_SPECIALITY",
                "unique_together": {("clinic", "speciality")},
            },
        ),
        migrations.CreateModel(
            name="ClinicTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name="id"
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="clinic_test", to="medicalApp.clinic"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="clinic_test", to="medicalApp.test"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Test",
                "verbose_name_plural": "Clinics Tests",
                "db_table": "MED_CLINIC_TEST",
                "unique_together": {("clinic", "test")},
            },
        ),
    ]
