version: "3.8"

services:
  postgres-master:
    container_name: wirachain_master
    image: postgres:14.1-alpine
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/backend/primary.conf:/etc/postgresql.conf:ro
      - ./docker/backend/pg_hba.conf:/etc/pg_hba.conf:ro
    env_file:
      - ./backend/src/environments/.env.development
    networks:
      - pg_net

  postgres-first-replica:
    container_name: wirachain_first_replica
    image: postgres:14.1-alpine
    user: "postgres"
    restart: unless-stopped
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/src/environments/.env.development
    networks:
      - pg_net
    depends_on:
      - postgres-master
    command: [
        "bash",
        "-c",
        "until pg_isready -h postgres-master -U $${POSTGRES_USER}; do sleep 6; done;
        rm -rf /var/lib/postgresql/data/*;
        PGPASSWORD=$${POSTGRES_PASSWORD} pg_basebackup -h postgres-master -D /var/lib/postgresql/data -U $${POSTGRES_USER} -Fp -Xs -P -R;
        chown -R postgres:postgres /var/lib/postgresql/data;
        chmod 700 /var/lib/postgresql/data;
        exec postgres",
      ]

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - pg_net

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - ./docker/backend/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    env_file:
      - ./backend/src/environments/.env.development
    networks:
      - pg_net

  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        - ENV_TYPE=development
    env_file:
      - ./backend/src/environments/.env.development
    depends_on:
      - postgres-master
      - postgres-first-replica
    networks:
      - pg_net

  celery:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        - ENV_TYPE=development
    working_dir: /app/backend/src
    env_file:
      - ./backend/src/environments/.env.development
    depends_on:
      - rabbitmq
      - postgres-master
    networks:
      - pg_net

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        VITE_API_URL: "http://localhost:8000/api/v1/"
    environment:
      VITE_API_URL: "http://localhost:8000/api/v1/"
    restart: unless-stopped
    networks:
      - pg_net
    depends_on:
      - web

volumes:
  postgres_data: {}
  postgres_replica_data: {}
  static_volume: {}

networks:
  pg_net:
