version: "3.8"

services:
  postgres-master:
    container_name: wirachain_master
    image: postgres:14.1-alpine
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/backend/primary.conf:/etc/postgresql.conf
      - ./docker/backend/pg_hba.conf:/etc/pg_hba.conf
    env_file:
      - ./backend/src/environments/.env.development
    ports:
      - "5432:5432"
    networks:
      - pg_net

  postgres-first-replica:
    container_name: wirachain_first_replica
    image: postgres:14.1-alpine
    user: "postgres"
    restart: unless-stopped
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/src/environments/.env.development
    ports:
      - "5433:5432"
    networks:
      - pg_net
    depends_on:
      - postgres-master
    command: [
        "bash",
        "-c",
        "until pg_isready -h postgres-master -U $${POSTGRES_USER}; do sleep 6; done;
        rm -rf /var/lib/postgresql/data/*;
        PGPASSWORD=$${POSTGRES_PASSWORD} pg_basebackup -h postgres-master -D /var/lib/postgresql/data -U $${POSTGRES_USER} -Fp -Xs -P -R;
        chown -R postgres:postgres /var/lib/postgresql/data;
        chmod 700 /var/lib/postgresql/data;
        exec postgres",
      ]

  redis:
    container_name: wirachain_redis
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pg_net

  web:
    container_name: wirachain_django
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        - ENV_TYPE=development
    entrypoint:
      [
        "/app/docker/backend/wait-for-dbs.sh",
        "/app/docker/backend/server-entrypoint.sh",
      ]
    restart: unless-stopped
    volumes:
      - static_volume:/app/backend/src/mediafields
      - ./backend/htmlcov:/app/backend/htmlcov
    env_file:
      - ./backend/src/environments/.env.development
    environment:
      - ENV_TYPE=development
    ports:
      - "8000:8000"
    depends_on:
      - postgres-master
      - postgres-first-replica
    networks:
      - pg_net

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - ./docker/backend/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./backend/src/environments/.env.development
    networks:
      - pg_net

  celery:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        - ENV_TYPE=development
    command: celery -A core worker --loglevel=info
    working_dir: /app/backend/src
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - postgres-master
    env_file:
      - ./backend/src/environments/.env.development
    environment:
      - ENV_TYPE=development
      - DJANGO_SETTINGS_MODULE=core.settings.development
    networks:
      - pg_net

  frontend:
    container_name: wirachain_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        VITE_API_URL: "http://localhost:8000/api/v1/"
    environment:
      VITE_API_URL: "http://localhost:8000/api/v1/"
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - pg_net
    depends_on:
      - web

volumes:
  static_volume: {}
  postgres_data: {}
  postgres_replica_data: {}

networks:
  pg_net:
# docker compose down
# docker compose down -v
# docker compose up --build -d
