[pytest]
DJANGO_SETTINGS_MODULE = core.settings.test
python_files = test_*.py *_test.py
testpaths = tests
pythonpath = . src
addopts = --cov=src --cov-report html
; DATABASES["replica"]["TEST"] = {"MIRROR": "default"}