export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  RESEND_EMAIL: "/resend-email",
  FORGOT_PASSWORD: "/forgot-password",
  ACTIVATE_ACCOUNT: "/activate-account/:activate_code",
  DASHBOARD: "/dashboard",
  PROFILE: "/dashboard/profile",
  SETTING: "/dashboard/setting",
  CLINIC: "/dashboard/clinic",
  DOCTOR: "/dashboard/doctor",
  DISEASE: "/dashboard/disease",
  SPECIALITY: "/dashboard/speciality",
  TEST: "/dashboard/test",
  WAITING_LIST: "/dashboard/waiting-list",
  APPOINTMENT: "/dashboard/appointment",
  RESERVATION: "/dashboard/reservation",
  MEDICAL_RECORD: "/dashboard/medical-record",
};
