from medicalApp.serializers.ClinicSerializer import ClinicSerializer
from medicalApp.serializers.ClinicDoctorSerializer import ClinicDoctorSerializer
from medicalApp.serializers.DoctorSpecialitySerializer import DoctorSpecialitySerializer
from medicalApp.serializers.ClinicSpecialitySerializer import ClinicSpecialitySerializer
from medicalApp.serializers.ClinicTestSerializer import ClinicTestSerializer
from medicalApp.serializers.SpecialitySerializer import SpecialitySerializer
from medicalApp.serializers.TestSerializer import TestSerializer
from medicalApp.serializers.DiseaseSerializer import DiseaseSerializer
