from medicalApp.models.MedicalSpeciality import MedicalSpeciality
from medicalApp.models.MedicalTest import MedicalTest
from medicalApp.models.EnterpriseMedicalTest import EnterpriseMedicalTest
from medicalApp.models.EnterpriseMedicalSpeciality import EnterpriseMedicalSpeciality
from medicalApp.models.Clinic import Clinic
from medicalApp.models.ClinicDoctor import ClinicDoctor
from medicalApp.models.DoctorMedicalSpeciality import DoctorMedicalSpeciality
